
title: Youssef Yasser # your name (or website title) here
logo: "/formal.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Frontend Developer
  <br><br>
  <a href="mailto:youssefyasserfouda@yahoo.com">youssefyasserfouda@yahoo.com </a>
  <br>
  <a href="https://www.linkedin.com/in/youssef-yasser-133a91161/">LinkedIn Profile</a>
  <br>
  <a href="https://www.github.com/youssefyasser98/">Gihub</a> 
  <br>
  ### Phone Number : +20-01223864289 
  <br> 
  <span>Address : Cairo , Egypt</span>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>
  <br>

theme: jekyll-theme-minimal
